# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWRAssignment' do
  pod 'GoogleMaps'
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
